$\begin{bmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{bmatrix}$

In [1]:
import numpy as np
R = np.arange(1, 13).reshape(3, 4)
print(R)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
R[1,2] *= -1
print(R)

[[ 1  2  3  4]
 [ 5  6 -7  8]
 [ 9 10 11 12]]


In [3]:
R[0,2] -= 4
print(R)

[[ 1  2 -1  4]
 [ 5  6 -7  8]
 [ 9 10 11 12]]


In [4]:
R[:, 1] *= 2
print(R)

[[ 1  4 -1  4]
 [ 5 12 -7  8]
 [ 9 20 11 12]]


In [5]:
R[0, :] *= 3
print(R)

[[ 3 12 -3 12]
 [ 5 12 -7  8]
 [ 9 20 11 12]]
