In [1]:
import numpy as np
import numpy.matlib as ml
A = ml.matrix('1,2,3;4,5,6')
B = ml.matrix('1,-2,1; -2,3,4')
c = 2 #ml.matrix('2')
D = ml.ones((2,3))
E = ml.eye(3,3)
print(A, B, c, D, E, sep = '\n\n')

[[1 2 3]
 [4 5 6]]

[[ 1 -2  1]
 [-2  3  4]]

2

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
print(A+B)

[[ 2  0  4]
 [ 2  8 10]]


In [3]:
print(A+c)

[[3 4 5]
 [6 7 8]]


In [4]:
print(A+E)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [5]:
print(A-c)

[[-1  0  1]
 [ 2  3  4]]


In [6]:
print(c*A)

[[ 2  4  6]
 [ 8 10 12]]


In [8]:
print(A*B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
print(A*B.transpose())

[[ 0 16]
 [ 0 31]]
