In [9]:
import numpy as np
import numpy.matlib as ml
A = ml.matrix('1,2,3;4,5,6')
B = ml.matrix('1,-2,1; -2,3,4')
c = 2 #ml.matrix('2')
D = ml.ones((2,3))
E = ml.eye(3,3)
print(A, B, c, D, E, sep = '\n\n')

[[1 2 3]
 [4 5 6]]

[[ 1 -2  1]
 [-2  3  4]]

2

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(A+B)

[[ 2  0  4]
 [ 2  8 10]]


In [11]:
print(A+c)

[[3 4 5]
 [6 7 8]]


In [12]:
print(A+E)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [13]:
print(A-c)

[[-1  0  1]
 [ 2  3  4]]


In [14]:
print(c*A)

[[ 2  4  6]
 [ 8 10 12]]


In [15]:
print(np.matmul(A,B))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
print(np.matmul(A,B.transpose()))

[[ 0 16]
 [ 0 31]]
